"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
const uuid = /^[0-9a-f-]{36}$/i;
async function context() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login"); const { data: workspace } = await supabase.from("workspaces").select("id").eq("owner_id", user.id).maybeSingle(); if (!workspace) redirect("/onboarding"); return { supabase, user, workspace }; }
const optionalNumber = (value: FormDataEntryValue | null) => { const text = String(value ?? "").trim(); return text ? Number(text) : null; };

export async function createNutritionPlan(formData: FormData) {
  const name = String(formData.get("name") ?? "").trim(); const description = String(formData.get("description") ?? "").trim();
  const daily_calories = optionalNumber(formData.get("calories")); const protein_grams = optionalNumber(formData.get("protein")); const carbs_grams = optionalNumber(formData.get("carbs")); const fat_grams = optionalNumber(formData.get("fat"));
  if (!name || name.length > 120 || [daily_calories, protein_grams, carbs_grams, fat_grams].some(value => value !== null && (!Number.isInteger(value) || value < 0))) redirect("/nutrition-plans/new?error=invalid");
  const { supabase, user, workspace } = await context(); const { data, error } = await supabase.from("nutrition_plans").insert({ workspace_id: workspace.id, created_by: user.id, name, description: description || null, daily_calories, protein_grams, carbs_grams, fat_grams }).select("id").single();
  if (error || !data) redirect("/nutrition-plans/new?error=create"); revalidatePath("/nutrition-plans"); redirect(`/nutrition-plans/${data.id}`);
}
export async function addMeal(planId: string, formData: FormData) { if (!uuid.test(planId)) throw new Error("Invalid plan."); const name = String(formData.get("name") ?? "").trim(); const timing = String(formData.get("timing") ?? "").trim(); if (!name) throw new Error("Meal name is required."); const { supabase } = await context(); const { data: last } = await supabase.from("nutrition_meals").select("position").eq("nutrition_plan_id", planId).order("position", { ascending: false }).limit(1).maybeSingle(); const { error } = await supabase.from("nutrition_meals").insert({ nutrition_plan_id: planId, position: (last?.position ?? 0) + 1, name, timing: timing || null }); if (error) throw new Error("Unable to add meal."); revalidatePath(`/nutrition-plans/${planId}`); }
export async function addFood(planId: string, mealId: string, formData: FormData) { if (!uuid.test(planId) || !uuid.test(mealId)) throw new Error("Invalid meal."); const name = String(formData.get("name") ?? "").trim(); const amount = String(formData.get("amount") ?? "").trim(); const alternatives = String(formData.get("alternatives") ?? "").trim(); if (!name || !amount) throw new Error("Food and amount are required."); const { supabase } = await context(); const { data: last } = await supabase.from("nutrition_items").select("position").eq("nutrition_meal_id", mealId).order("position", { ascending: false }).limit(1).maybeSingle(); const { error } = await supabase.from("nutrition_items").insert({ nutrition_meal_id: mealId, position: (last?.position ?? 0) + 1, name, amount, alternatives: alternatives || null }); if (error) throw new Error("Unable to add food."); revalidatePath(`/nutrition-plans/${planId}`); }
export async function setNutritionStatus(planId: string, formData: FormData) { const status = String(formData.get("status")); if (!uuid.test(planId) || !["draft", "active", "archived"].includes(status)) throw new Error("Invalid status."); const { supabase, workspace } = await context(); const { error } = await supabase.from("nutrition_plans").update({ status }).eq("id", planId).eq("workspace_id", workspace.id); if (error) throw new Error("Unable to update plan."); revalidatePath("/nutrition-plans"); revalidatePath(`/nutrition-plans/${planId}`); }
export async function assignNutritionPlan(planId: string, formData: FormData) { const clientId = String(formData.get("clientId") ?? ""); const startsOn = String(formData.get("startsOn") ?? ""); if (!uuid.test(planId) || !uuid.test(clientId) || !/^\d{4}-\d{2}-\d{2}$/.test(startsOn)) throw new Error("Invalid assignment."); const { supabase, user, workspace } = await context(); const { error } = await supabase.from("nutrition_plan_assignments").insert({ workspace_id: workspace.id, client_id: clientId, nutrition_plan_id: planId, assigned_by: user.id, starts_on: startsOn }); if (error) throw new Error("Unable to assign nutrition plan."); revalidatePath(`/nutrition-plans/${planId}`); }
