import Link from "next/link";
import { createWorkoutPlan } from "../actions";
import { Button, ButtonLink } from "@/app/components/ui/Button";
import { Alert } from "@/app/components/ui/Feedback";
import { Field, Input, Textarea } from "@/app/components/ui/FormControls";

export default async function NewWorkoutPlanPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const query = await searchParams;
  return <main className="px-4 py-6 sm:px-6 lg:px-10 lg:py-9"><div className="mx-auto max-w-3xl"><Link href="/workout-plans" className="text-sm font-medium text-brand">← Plan library</Link><div className="mt-6 overflow-hidden rounded-[2rem] border border-border bg-surface"><div className="bg-brand-strong p-7 text-white sm:p-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-accent">New training system</p><h1 className="mt-3 text-3xl font-semibold">Start with the intent.</h1><p className="mt-2 max-w-xl text-sm leading-6 text-white/65">Name the outcome this plan creates. You’ll add training days and exercises next.</p></div><form action={createWorkoutPlan} className="space-y-6 p-7 sm:p-10">{query.error && <Alert tone="error">We couldn’t create this plan. Check the details and try again.</Alert>}<Field label="Plan name" htmlFor="name"><Input id="name" name="name" required maxLength={120} placeholder="e.g. 12-week strength foundation" /></Field><Field label="Course duration (weeks)" htmlFor="durationWeeks" hint="Access expires automatically after this many weeks."><Input id="durationWeeks" name="durationWeeks" type="number" min="1" max="104" defaultValue="12" required /></Field><Field label="Coaching intent" htmlFor="description"><Textarea id="description" name="description" maxLength={5000} rows={5} placeholder="Who is it for, and what will it help them achieve?" /></Field><div className="flex flex-wrap gap-3"><Button type="submit">Create and add days</Button><ButtonLink href="/workout-plans" variant="ghost">Cancel</ButtonLink></div></form></div></div></main>;
}
